package com.aneal.bng.ch8;
/**
 * The limit method limits the number of elements generated by the supplier to 15;
 * otherwise, the generated stream is infinite. If we make use of lambda expressions, the
 * previous code reduces to
 */

import java.util.Random;
import java.util.stream.Stream;

public class StreamBuilderDemo01 {
    public static void main(String[] args) {

        Stream<Integer> generated = Stream.generate(
                () -> new Random().nextInt(300) + 1
        ).limit(15);
    }
}
